function TranslateCap(str)
    return str:gsub("_", " ")
end

Config.DefaultWeaponTints = {
    [0] = TranslateCap("tint_default"),
    [1] = TranslateCap("tint_green"),
    [2] = TranslateCap("tint_gold"),
    [3] = TranslateCap("tint_pink"),
    [4] = TranslateCap("tint_army"),
    [5] = TranslateCap("tint_lspd"),
    [6] = TranslateCap("tint_orange"),
    [7] = TranslateCap("tint_platinum"),
}
Config.MK2WeaponTints = {
    [0]  = TranslateCap('tint_classic_black'),
    [1]  = TranslateCap('tint_classic_gray'),
    [2]  = TranslateCap('tint_classic_two_tone'),
    [3]  = TranslateCap('tint_classic_white'),
    [4]  = TranslateCap('tint_classic_beige'),
    [5]  = TranslateCap('tint_classic_green'),
    [6]  = TranslateCap('tint_classic_blue'),
    [7]  = TranslateCap('tint_classic_earth'),
    [8]  = TranslateCap('tint_classic_brown_black'),
    [9]  = TranslateCap('tint_contrast_red'),
    [10] = TranslateCap('tint_contrast_blue'),
    [11] = TranslateCap('tint_contrast_yellow'),
    [12] = TranslateCap('tint_contrast_orange'),
    [13] = TranslateCap('tint_bold_pink'),
    [14] = TranslateCap('tint_bold_purple_yellow'),
    [15] = TranslateCap('tint_bold_orange'),
    [16] = TranslateCap('tint_bold_green_purple'),
    [17] = TranslateCap('tint_bold_red_feat'),
    [18] = TranslateCap('tint_bold_green_feat'),
    [19] = TranslateCap('tint_bold_cyan_feat'),
    [20] = TranslateCap('tint_bold_yellow_feat'),
    [21] = TranslateCap('tint_bold_red_white'),
    [22] = TranslateCap('tint_bold_blue_white'),
    [23] = TranslateCap('tint_metallic_gold'),
    [24] = TranslateCap('tint_metallic_platinum'),
    [25] = TranslateCap('tint_metallic_gray_lilac'),
    [26] = TranslateCap('tint_metallic_purple_lime'),
    [27] = TranslateCap('tint_metallic_red'),
    [28] = TranslateCap('tint_metallic_green'),
    [29] = TranslateCap('tint_metallic_blue'),
    [30] = TranslateCap('tint_metallic_white_aqua'),
    [31] = TranslateCap('tint_metallic_orange_yellow'),
    [32] = TranslateCap('tint_metallic_red_yellow')
}

Config.Weapons = {
    -- Melee
    { name = "WEAPON_DAGGER", label = TranslateCap("weapon_dagger"), components = {} },
    { name = "WEAPON_BAT", label = TranslateCap("weapon_bat"), components = {} },
    { name = "WEAPON_BATTLEAXE", label = TranslateCap("weapon_battleaxe"), components = {} },
    { name = "WEAPON_KNUCKLE", label = TranslateCap("weapon_knuckle"), components = {} },
    { name = "WEAPON_BOTTLE", label = TranslateCap("weapon_bottle"), components = {} },
    { name = "WEAPON_CROWBAR", label = TranslateCap("weapon_crowbar"), components = {} },
    { name = "WEAPON_FLASHLIGHT", label = TranslateCap("weapon_flashlight"), components = {} },
    { name = "WEAPON_GOLFCLUB", label = TranslateCap("weapon_golfclub"), components = {} },
    { name = "WEAPON_HAMMER", label = TranslateCap("weapon_hammer"), components = {} },
    { name = "WEAPON_HATCHET", label = TranslateCap("weapon_hatchet"), components = {} },
    { name = "WEAPON_KNIFE", label = TranslateCap("weapon_knife"), components = {} },
    { name = "WEAPON_MACHETE", label = TranslateCap("weapon_machete"), components = {} },
    { name = "WEAPON_NIGHTSTICK", label = TranslateCap("weapon_nightstick"), components = {} },
    { name = "WEAPON_WRENCH", label = TranslateCap("weapon_wrench"), components = {} },
    { name = "WEAPON_POOLCUE", label = TranslateCap("weapon_poolcue"), components = {} },
    { name = "WEAPON_STONE_HATCHET", label = TranslateCap("weapon_stone_hatchet"), components = {} },
    { name = "WEAPON_SWITCHBLADE", label = TranslateCap("weapon_switchblade"), components = {} },
    -- Handguns
    {
        name = "WEAPON_APPISTOL",
        label = TranslateCap("weapon_appistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_APPISTOL_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    { name = "WEAPON_CERAMICPISTOL", label = TranslateCap("weapon_ceramicpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` } },
    {
        name = "WEAPON_COMBATPISTOL",
        label = TranslateCap("weapon_combatpistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_COMBATPISTOL_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    { name = "WEAPON_DOUBLEACTION", label = TranslateCap("weapon_doubleaction"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` } },
    { name = "WEAPON_NAVYREVOLVER", label = TranslateCap("weapon_navyrevolver"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` } },
    { name = "WEAPON_FLAREGUN", label = TranslateCap("weapon_flaregun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_flaregun"), hash = `AMMO_FLAREGUN` } },
    { name = "WEAPON_GADGETPISTOL", label = TranslateCap("weapon_gadgetpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` } },
    {
        name = "WEAPON_HEAVYPISTOL",
        label = TranslateCap("weapon_heavypistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_HEAVYPISTOL_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    {
        name = "WEAPON_REVOLVER",
        label = TranslateCap("weapon_revolver"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_REVOLVER_CLIP_02` },
        },
    },
    {
        name = "WEAPON_REVOLVER_MK2",
        label = TranslateCap("weapon_revolver_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_REVOLVER_MK2_CLIP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP_02` },
        },
    },
    { name = "WEAPON_MARKSMANPISTOL", label = TranslateCap("weapon_marksmanpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` } },
    {
        name = "WEAPON_PISTOL",
        label = TranslateCap("weapon_pistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_PISTOL_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP_02` },
        },
    },
    {
        name = "WEAPON_PISTOL_MK2",
        label = TranslateCap("weapon_pistol_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_PISTOL_MK2_CLIP_02` },
            { name = "scope", label = TranslateCap("component_scope"), hash = `COMPONENT_AT_PI_RAIL` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH_02` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP_02` },
            },
    },
    {
        name = "WEAPON_PISTOL50",
        label = TranslateCap("weapon_pistol50"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_PISTOL50_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_SNSPISTOL",
        label = TranslateCap("weapon_snspistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SNSPISTOL_CLIP_02` },
        },
    },
    {
        name = "WEAPON_SNSPISTOL_MK2",
        label = TranslateCap("weapon_snspistol_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SNSPISTOL_MK2_CLIP_02` },
            { name = "scope", label = TranslateCap("component_scope"), hash = `COMPONENT_AT_PI_RAIL_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH_03` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP_02` },
        },
    },
    { name = "WEAPON_STUNGUN", label = TranslateCap("weapon_stungun"), tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_STUNROD", label = TranslateCap("weapon_stunrod"), tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_RAYPISTOL", label = TranslateCap("weapon_raypistol"), tints = Config.DefaultWeaponTints, components = {} },
    {
        name = "WEAPON_VINTAGEPISTOL",
        label = TranslateCap("weapon_vintagepistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_VINTAGEPISTOL_CLIP_02` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    -- Shotguns
    {
        name = "WEAPON_ASSAULTSHOTGUN",
        label = TranslateCap("weapon_assaultshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_ASSAULTSHOTGUN_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    { name = "WEAPON_AUTOSHOTGUN", label = TranslateCap("weapon_autoshotgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` } },
    {
        name = "WEAPON_BULLPUPSHOTGUN",
        label = TranslateCap("weapon_bullpupshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_COMBATSHOTGUN",
        label = TranslateCap("weapon_combatshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    { name = "WEAPON_DBSHOTGUN", label = TranslateCap("weapon_dbshotgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` } },
    {
        name = "WEAPON_HEAVYSHOTGUN",
        label = TranslateCap("weapon_heavyshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_HEAVYSHOTGUN_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    { name = "WEAPON_MUSKET", label = TranslateCap("weapon_musket"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SHOTGUN` } },
    {
        name = "WEAPON_PUMPSHOTGUN",
        label = TranslateCap("weapon_pumpshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_SR_SUPP` },
        },
    },
    {
        name = "WEAPON_PUMPSHOTGUN_MK2",
        label = TranslateCap("weapon_pumpshotgun_mk2"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_SR_SUPP_03` },
        },
    },
    {
        name = "WEAPON_SAWNOFFSHOTGUN",
        label = TranslateCap("weapon_sawnoffshotgun"),
        ammo = { label = TranslateCap("ammo_shells"), hash = `AMMO_SHOTGUN` },
        tints = Config.DefaultWeaponTints,
        components = {},
    },
    -- SMG & LMG
    {
        name = "WEAPON_ASSAULTSMG",
        label = TranslateCap("weapon_assaultsmg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_ASSAULTSMG_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_COMBATMG",
        label = TranslateCap("weapon_combatmg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_COMBATMG_CLIP_02` },
        },
    },
    {
        name = "WEAPON_COMBATMG_MK2",
        label = TranslateCap("weapon_combatmg_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MG` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_COMBATMG_MK2_CLIP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
        },
    },
    {
        name = "WEAPON_COMBATPDW",
        label = TranslateCap("weapon_combatpdw"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_COMBATPDW_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
        },
    },
    {
        name = "WEAPON_GUSENBERG",
        label = TranslateCap("weapon_gusenberg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_GUSENBERG_CLIP_02` },
        },
    },
    {
        name = "WEAPON_MACHINEPISTOL",
        label = TranslateCap("weapon_machinepistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MACHINEPISTOL_CLIP_02` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    {
        name = "WEAPON_MG",
        label = TranslateCap("weapon_mg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MG_CLIP_02` },
        },
    },
    {
        name = "WEAPON_MICROSMG",
        label = TranslateCap("weapon_microsmg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MICROSMG_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_MINISMG",
        label = TranslateCap("weapon_minismg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MINISMG_CLIP_02` },
        },
    },
    {
        name = "WEAPON_SMG",
        label = TranslateCap("weapon_smg"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SMG_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    {
        name = "WEAPON_TECPISTOL",
        label = TranslateCap("weapon_tecpistol"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_TECPISTOL_CLIP_02` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_SMG_MK2",
        label = TranslateCap("weapon_smg_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SMG_MK2_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS_SMG` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_PI_SUPP` },
        },
    },
    { name = "WEAPON_RAYCARBINE", label = TranslateCap("weapon_raycarbine"), ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SMG` }, tints = Config.DefaultWeaponTints, components = {} },
    -- Rifles
    {
        name = "WEAPON_ADVANCEDRIFLE",
        label = TranslateCap("weapon_advancedrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_ADVANCEDRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE",
        label = TranslateCap("weapon_assaultrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_ASSAULTRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE_MK2",
        label = TranslateCap("weapon_assaultrifle_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_ASSAULTRIFLE_MK2_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE",
        label = TranslateCap("weapon_bullpuprifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_BULLPUPRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE_MK2",
        label = TranslateCap("weapon_bullpuprifle_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_BULLPUPRIFLE_MK2_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE",
        label = TranslateCap("weapon_carbinerifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_CARBINERIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE_MK2",
        label = TranslateCap("weapon_carbinerifle_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_CARBINERIFLE_MK2_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_COMPACTRIFLE",
        label = TranslateCap("weapon_compactrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_COMPACTRIFLE_CLIP_02` },
        },
    },
    {
        name = "WEAPON_MILITARYRIFLE",
        label = TranslateCap("weapon_militaryrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MILITARYRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE",
        label = TranslateCap("weapon_specialcarbine"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SPECIALCARBINE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SCOPE_MEDIUM` },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE_MK2",
        label = TranslateCap("weapon_specialcarbine_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_SPECIALCARBINE_MK2_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
        },
    },
    {
        name = "WEAPON_HEAVYRIFLE",
        label = TranslateCap("weapon_heavyrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_HEAVYRIFLE_CLIP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_HEAVYRIFLE_SIGHT_01` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    -- Sniper
    {
        name = "WEAPON_HEAVYSNIPER",
        label = TranslateCap("weapon_heavysniper"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = TranslateCap("component_scope"), hash = `COMPONENT_AT_SCOPE_LARGE` },
            { name = "scope_advanced", label = TranslateCap("component_scope_advanced"), hash = `COMPONENT_AT_SCOPE_MAX` },
        },
    },
    {
        name = "WEAPON_HEAVYSNIPER_MK2",
        label = TranslateCap("weapon_heavysniper_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_HEAVYSNIPER_MK2_CLIP_02` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_SR_SUPP_03` },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE",
        label = TranslateCap("weapon_marksmanrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MARKSMANRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE_MK2",
        label = TranslateCap("weapon_marksmanrifle_mk2"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_MARKSMANRIFLE_MK2_CLIP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SIGHTS` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
        },
    },
    {
        name = "WEAPON_SNIPERRIFLE",
        label = TranslateCap("weapon_sniperrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = TranslateCap("component_scope"), hash = `COMPONENT_AT_SCOPE_LARGE` },
            { name = "scope_advanced", label = TranslateCap("component_scope_advanced"), hash = `COMPONENT_AT_SCOPE_MAX` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
            { name = "luxary_finish", label = TranslateCap("component_luxary_finish"), hash = `COMPONENT_SNIPERRIFLE_VARMOD_LUXE` },
        },
    },
    -- Heavy / Launchers
    {
        name = "WEAPON_COMPACTLAUNCHER",
        label = TranslateCap("weapon_compactlauncher"),
        tints = Config.DefaultWeaponTints,
        components = {},
        ammo = { label = TranslateCap("ammo_grenadelauncher"), hash = `AMMO_GRENADELAUNCHER` },
    },
    { name = "WEAPON_FIREWORK", label = TranslateCap("weapon_firework"), components = {}, ammo = { label = TranslateCap("ammo_firework"), hash = `AMMO_FIREWORK` } },
    {
        name = "WEAPON_GRENADELAUNCHER",
        label = TranslateCap("weapon_grenadelauncher"),
        tints = Config.DefaultWeaponTints,
        components = {},
        ammo = { label = TranslateCap("ammo_grenadelauncher"), hash = `AMMO_GRENADELAUNCHER` },
    },
    { name = "WEAPON_HOMINGLAUNCHER", label = TranslateCap("weapon_hominglauncher"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rockets"), hash = `AMMO_HOMINGLAUNCHER` } },
    { name = "WEAPON_MINIGUN", label = TranslateCap("weapon_minigun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MINIGUN` } },
    { name = "WEAPON_RAILGUN", label = TranslateCap("weapon_railgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RAILGUN` } },
    { name = "WEAPON_RPG", label = TranslateCap("weapon_rpg"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rockets"), hash = `AMMO_RPG` } },
    { name = "WEAPON_RAYMINIGUN", label = TranslateCap("weapon_rayminigun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_MINIGUN` } },
    -- Thrown
    { name = "WEAPON_BALL", label = TranslateCap("weapon_ball"), components = {}, ammo = { label = TranslateCap("ammo_ball"), hash = `AMMO_BALL` }, throwable = true },
    { name = "WEAPON_BZGAS", label = TranslateCap("weapon_bzgas"), components = {}, ammo = { label = TranslateCap("ammo_bzgas"), hash = `AMMO_BZGAS` }, throwable = true },
    { name = "WEAPON_FLARE", label = TranslateCap("weapon_flare"), components = {}, ammo = { label = TranslateCap("ammo_flare"), hash = `AMMO_FLARE` }, throwable = true },
    { name = "WEAPON_GRENADE", label = TranslateCap("weapon_grenade"), components = {}, ammo = { label = TranslateCap("ammo_grenade"), hash = `AMMO_GRENADE` }, throwable = true },
    { name = "WEAPON_PETROLCAN", label = TranslateCap("weapon_petrolcan"), components = {}, ammo = { label = TranslateCap("ammo_petrol"), hash = `AMMO_PETROLCAN` }, throwable = true },
    { name = "WEAPON_HAZARDCAN", label = TranslateCap("weapon_hazardcan"), components = {}, ammo = { label = TranslateCap("ammo_petrol"), hash = `AMMO_PETROLCAN` }, throwable = true },
    { name = "WEAPON_MOLOTOV", label = TranslateCap("weapon_molotov"), components = {}, ammo = { label = TranslateCap("ammo_molotov"), hash = `AMMO_MOLOTOV` }, throwable = true },
    { name = "WEAPON_PROXMINE", label = TranslateCap("weapon_proxmine"), components = {}, ammo = { label = TranslateCap("ammo_proxmine"), hash = `AMMO_PROXMINE` }, throwable = true },
    { name = "WEAPON_PIPEBOMB", label = TranslateCap("weapon_pipebomb"), components = {}, ammo = { label = TranslateCap("ammo_pipebomb"), hash = `AMMO_PIPEBOMB` }, throwable = true },
    { name = "WEAPON_SNOWBALL", label = TranslateCap("weapon_snowball"), components = {}, ammo = { label = TranslateCap("ammo_snowball"), hash = `AMMO_SNOWBALL` }, throwable = true },
    { name = "WEAPON_STICKYBOMB", label = TranslateCap("weapon_stickybomb"), components = {}, ammo = { label = TranslateCap("ammo_stickybomb"), hash = `AMMO_STICKYBOMB` }, throwable = true },
    { name = "WEAPON_SMOKEGRENADE", label = TranslateCap("weapon_smokegrenade"), components = {}, ammo = { label = TranslateCap("ammo_smokebomb"), hash = `AMMO_SMOKEGRENADE` }, throwable = true },
    -- Tools
    { name = "WEAPON_FIREEXTINGUISHER", label = TranslateCap("weapon_fireextinguisher"), components = {}, ammo = { label = TranslateCap("ammo_charge"), hash = `AMMO_FIREEXTINGUISHER` } },
    { name = "WEAPON_DIGISCANNER", label = TranslateCap("weapon_digiscanner"), components = {} },
    { name = "GADGET_PARACHUTE", label = TranslateCap("gadget_parachute"), components = {}, throwable = true },
    {
        name = "WEAPON_TACTICALRIFLE",
        label = TranslateCap("weapon_tactilerifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_TACTICALRIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH_REH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP_02` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SCOPE_MACRO` },
        },
    },
    {
        name = "WEAPON_BATTLERIFLE",
        label = TranslateCap("weapon_battlerifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RIFLE` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_BATTLERIFLE_CLIP_02` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_AR_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_AR_SUPP` },
            { name = "scope_holo", label = TranslateCap("component_scope_holo"), hash = `COMPONENT_AT_SCOPE_MACRO` },
        },
    },
    {
        name = "WEAPON_SNOWLAUNCHER",
        label = TranslateCap("weapon_snowlauncher"),
        ammo = { label = TranslateCap("ammo_snowball"), hash = `AMMO_SNOWLAUNCHER` },
        tints = Config.DefaultWeaponTints,
        components = {},
    },
    {
        name = "WEAPON_HACKINGDEVICE",
        label = TranslateCap("weapon_hackingdevice"),
        tints = Config.DefaultWeaponTints,
        components = {},
    },
    {
        name = "WEAPON_PRECISIONRIFLE",
        label = TranslateCap("weapon_precisionrifle"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_SNIPER` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_PRECISIONRIFLE_CLIP_01` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_AT_SR_SUPP_03` },
        },
    },
    { name = "WEAPON_METALDETECTOR", label = TranslateCap("weapon_metaldetector"), components = {} },
    {
        name = "WEAPON_PISTOLXM3",
        label = TranslateCap("weapon_pistolxm3"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_PISTOL` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_extended", label = TranslateCap("component_clip_extended"), hash = `COMPONENT_PISTOLXM3_CLIP_01` },
            { name = "flashlight", label = TranslateCap("component_flashlight"), hash = `COMPONENT_AT_PI_FLSH` },
            { name = "suppressor", label = TranslateCap("component_suppressor"), hash = `COMPONENT_PISTOLXM3_SUPP` },
        },
    },
    { name = "WEAPON_ACIDPACKAGE", label = TranslateCap("weapon_acidpackage"), components = {}, throwable = true },
    { name = "WEAPON_CANDYCANE", label = TranslateCap("weapon_candycane"), components = {} },
    {
        name = "WEAPON_RAILGUNXM3",
        label = TranslateCap("weapon_railgunxm3"),
        ammo = { label = TranslateCap("ammo_rounds"), hash = `AMMO_RAILGUN` },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = TranslateCap("component_clip_default"), hash = `COMPONENT_RAILGUNXM3_CLIP_01` },
        },
    },
}